import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    target: 'node18',
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'plugins/apiMock': resolve(__dirname, 'src/plugins/apiMock.ts'),
        'plugins/autoAlias': resolve(__dirname, 'src/plugins/autoAlias.ts'),
        'plugins/bannerNotice': resolve(__dirname, 'src/plugins/bannerNotice.ts'),
        'plugins/buildLogModifier': resolve(__dirname, 'src/plugins/buildLogModifier.ts'),
        'plugins/buildScorer': resolve(__dirname, 'src/plugins/buildScorer.ts'),
        'plugins/cacheCleaner': resolve(__dirname, 'src/plugins/cacheCleaner.ts'),
        'plugins/codeSplit': resolve(__dirname, 'src/plugins/codeSplit.ts'),
        'plugins/compression': resolve(__dirname, 'src/plugins/compression.ts'),
        'plugins/convertCssRootToHost': resolve(__dirname, 'src/plugins/convertCssRootToHost.ts'),
        'plugins/customConfig': resolve(__dirname, 'src/plugins/customConfig.ts'),
        'plugins/deadCodeScanner': resolve(__dirname, 'src/plugins/deadCodeScanner.ts'),
        'plugins/devFallback': resolve(__dirname, 'src/plugins/devFallback.ts'),
        'plugins/envLoader': resolve(__dirname, 'src/plugins/envLoader.ts'),
        'plugins/envValidator': resolve(__dirname, 'src/plugins/envValidator.ts'),
        'plugins/fontLocalizer': resolve(__dirname, 'src/plugins/fontLocalizer.ts'),
        'plugins/htmlMeta': resolve(__dirname, 'src/plugins/htmlMeta.ts'),
        'plugins/imageToCdn': resolve(__dirname, 'src/plugins/imageToCdn.ts'),
        'plugins/jsAsJsx': resolve(__dirname, 'src/plugins/jsAsJsx.ts'),
        'plugins/licenseNotice': resolve(__dirname, 'src/plugins/licenseNotice.ts'),
        'plugins/postcssShadowDom': resolve(__dirname, 'src/plugins/postcssShadowDom.ts'),
        'plugins/proxyRedirects': resolve(__dirname, 'src/plugins/proxyRedirects.ts'),
        'plugins/publicCssManage': resolve(__dirname, 'src/plugins/publicCssManage.ts'),
        'plugins/resourceHints': resolve(__dirname, 'src/plugins/resourceHints.ts'),
        'plugins/securityHeaders': resolve(__dirname, 'src/plugins/securityHeaders.ts'),
        'plugins/svgSprite': resolve(__dirname, 'src/plugins/svgSprite.ts'),
        'utils/logger': resolve(__dirname, 'src/utils/logger.ts'),
      },
      formats: ['es'],
      fileName: (_format, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      external: [
        'vite',
        'postcss',
        /^node:.*/,
        'fs',
        'path',
        'url',
        'zlib',
        'http',
        'https',
        'crypto',
        'buffer',
        'events',
        'stream',
        'os',
      ],
    },
    sourcemap: false,
    minify: 'esbuild',
    emptyOutDir: true,
  },
});
